### ISSUE TITLE
Splitting %env over multiple lines

### ISSUE THREAD

**Issue by adamschmidt** [tripl-ai/arc-jupyter#3]
Would be great to be able to split `%env` cells over multiple lines, particularly where there are a lot of them and/or the length of the line exceeds the editor control width.

At the moment, they can only be set in a single line and the horizontal scrolling blocks visibility of what's in the cell

**Comment by seddonm1** [comment]
good catch.

this has been released as 1.3.0. supports `%env` and `%conf`
